name: test-on-merge

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Sync project (create venv + dev deps)
        run: uv sync

      - name: Run tests
        # env:
        #   PYTHONPATH: src # srcレイアウトをimport可に
        # run: uv run pytest -q
        run: uv run pytest -q
